import localFont from "next/font/local";
import { BibleDataProvider } from '../context/BibleDataContext';
import { MetaProvider } from '../context/MetaContext.jsx';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "IPray Daily",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <BibleDataProvider>
          <MetaProvider>
            {children}
          </MetaProvider>
        </BibleDataProvider>
      </body>
    </html>
  );
}
